name: pushing tag version for release

on:
  push:
    branches:
      - master

    tags:
      - v*

jobs:
  build:
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${{ steps.get_version.outputs.version-without-v }}" >> $GITHUB_ENV

      - name: Build and generate NuGet package
        run: |
          dotnet build -c Release -p:Version=${RELEASE_VERSION}
          dotnet pack -c Release -p:Version=${RELEASE_VERSION} -o out
        working-directory: Unitee.EventDriven.AzureServiceBus

      - name: Build and generate NuGet package
        run: |
          dotnet build -c Release -p:Version=${RELEASE_VERSION}
          dotnet pack -c Release -p:Version=${RELEASE_VERSION} -o out
        working-directory: Unitee.EventDriven.RedisStream

      - name: Build and generate NuGet package
        run: |
          dotnet build -c Release -p:Version=${RELEASE_VERSION}
          dotnet pack -c Release -p:Version=${RELEASE_VERSION} -o out
        working-directory: Unitee.EventDriven.Abstraction

      - name: Push generated package
        run: dotnet nuget push ./out/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate -n
        working-directory: Unitee.EventDriven.AzureServiceBus

      - name: Push generated package
        run: dotnet nuget push ./out/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate -n
        working-directory: Unitee.EventDriven.RedisStream

      - name: Push generated package
        run: dotnet nuget push ./out/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate -n
        working-directory: Unitee.EventDriven.Abstraction
